name: Combine Rules

on:
  schedule:
    - cron: '0 5 * * 0'  # Runs at 5:00 UTC every Sunday
  workflow_dispatch:      # Allows manual trigger

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run combine script
        run: bun run combine-rules

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/rules.db.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update rules.db.json [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 